name: '🌟 update - starred'

on:
  schedule:
    - cron: '30 0 * * *'
  workflow_dispatch:

concurrency:
  group: starred-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

env:
  MESSAGE: '🌟 update'

jobs:
  starred:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Python 3.12
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'
        cache: 'pip'
        cache-dependency-path: 'requirements-starred.txt'
    - name: Install dependencies and starred
      run: |
        python -m pip install --upgrade pip
        pip install --requirement requirements-starred.txt
    - name: update repo category by language
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        USERNAME: ${{ github.repository_owner }}
        REPOSITORY: ${{ github.event.repository.name }}
      run: |
        starred \
          --username "${USERNAME}" \
          --repository "${REPOSITORY}" \
          --sort \
          --token "${TOKEN}" \
          --message "${MESSAGE}" \
          --filename stars.md
    - name: update repo category by topic
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        USERNAME: ${{ github.repository_owner }}
        REPOSITORY: ${{ github.event.repository.name }}
      run: |
        starred \
          --username "${USERNAME}" \
          --repository "${REPOSITORY}" \
          --sort \
          --token "${TOKEN}" \
          --message "${MESSAGE}" \
          --topic \
          --topic_limit 500 \
          --filename topics.md