name: '🌟 update'

on:
  schedule:
    - cron: '30 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

env:
  MESSAGE: '🌟 update'

jobs:
  README:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install Package
        run: 'npm install'
      - name: Get repository name
        run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
      - name: Update Repo
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          REPOSITORY: ${{ env.REPOSITORY_NAME }}
        run: |
          npx stargazed \
            --username "${USERNAME}" \
            --token "${TOKEN}" \
            --repository "${REPOSITORY}" \
            --message "${MESSAGE}" \
            --sort
  